# Generated by Django 3.1.7 on 2021-03-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articals',
            new_name='Articales',
        ),
        migrations.AlterModelOptions(
            name='articales',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
