# Generated by Django 3.1.7 on 2021-03-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210312_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articales',
            new_name='Articles',
        ),
    ]
